[2018-10-02 17:14:33,058][ERROR][assign_task.py:30] In API calling assign_task_query_response
[2018-10-02 17:16:34,254][ERROR][assign_task.py:30] In API calling assign_task_query_response
[2018-10-02 17:17:29,924][ERROR][assign_task.py:30] In API calling assign_task_query_response
