[2018-10-08 01:41:59,145][ERROR][assign_task.py:30] In API calling assign_task_query_response
